### ISSUE TITLE
[BUG] Tests failing time after time

### ISSUE THREAD

**Issue by ebwinters** [disease-sh/API#875]
We are failing tests because in gov endpoints, when one scrape fails, they all go down. The tests are also running for 1 hour, the hard limit.

Some logs from latest test run scraping: 
```
 [2020-09-22T20:13:53.600Z]: Finished NYT scraping!
covid-api-app-test | [2020-09-22T20:13:57.353Z]: Apple Data successfully retrieved
covid-api-app-test | [2020-09-22T20:13:57.353Z]: Finished Apple scraping!
covid-api-app-test | {
covid-api-app-test |   message: '[2020-09-22T20:13:58.383Z] ERROR: Error: Requesting UK Gov Data failed!',
covid-api-app-test |   error: 'certificate has expired',
covid-api-app-test |   stack: 'Error: certificate has expired\n' +
covid-api-app-test |     '    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n' +
covid-api-app-test |     '    at TLSSocket.emit (events.js:314:20)\n' +
covid-api-app-test |     '    at TLSSocket.EventEmitter.emit (domain.js:486:12)\n' +
covid-api-app-test |     '    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n' +
covid-api-app-test |     '    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)'
covid-api-app-test | }
covid-api-app-test | {
covid-api-app-test |   message: '[2020-09-22T20:13:58.385Z] ERROR: Error: Requesting Gov data failed!',
covid-api-app-test |   error: "Cannot read property 'UK' of null",
covid-api-app-test |   stack: "TypeError: Cannot read property 'UK' of null\n" +
covid-api-app-test |     '    at _resolveData (/home/container/scrapers/covid-19/govScrapers/getGovData.js:30:28)\n' +
covid-api-app-test |     '    at runMicrotasks (<anonymous>)\n' +
covid-api-app-test |     '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
covid-api-app-test |     '    at async Promise.all (index 10)\n' +
covid-api-app-test |     '    at async govData (/home/container/scrapers/covid-19/govScrapers/getGovData.js:34:3)\n' +
covid-api-app-test |     '    at async excecuteScraperGov (/home/container/routes/instances.js:56:4)\n' +
covid-api-app-test |     '    at async Context.<anonymous> (/home/container/tests/mochaSetup.spec.js:30:3)'
covid-api-app-test | }
```

Test results all gov tests fail like this:
```
45) TESTING /v3/covid-19/gov/south africa
covid-api-app-test |        /v3/covid-19/gov/south africa correct data:
covid-api-app-test |      Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/container/tests/v3/covid-19/api_gov.spec.js)
covid-api-app-test |       at listOnTimeout (internal/timers.js:554:17)
covid-api-app-test |       at processTimers (internal/timers.js:497:7)
```

**Comment by ebwinters** [comment]
Oddly enough, in the live API, other countries are updating correctly - here's an Italy entry:
```JSON
{
"updated": 1600777195349,
"region": "Abruzzo",
"lat": "42.35122196",
"long": "13.39843823",
"hospitalizedWithSymptoms": 58,
"intensiveCare": 5,
"totalHospitalized": 63,
"homeIsolation": 676,
"newCases": 72,
"totalCases": 4209,
"recovered": 2995,
"deaths": 475
},
```
UK on the other hand is out of date. If scraping works for other countries in prod why not in testing??

**Comment by ebwinters** [comment]
Columbia is the culprit, returning this response: 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/4297028/93962383-bf67ee00-fd28-11ea-965c-04b4b83e24d9.png">

**Comment by Collin-St** [comment]
#876
